name: Stevelok
favicon: null
layout_spectrum: 0
typography_spectrum: 0.37176
title: Exploration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#555259'
    - '#a8a6ab'
    - '#847f85'
  brandStrength: 0.75
  lightness: 0.04657034738920629
  saturation: 0.7278537799138576
  rhythmicContrast: 0.04442581906914711
purpose: []
