name: Stevelok
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48919
title: Exploration
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#922850'
    - '#01336e'
    - '#6a88ab'
    - '#cdd9e8'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
